### ISSUE TITLE
[ TEST ] Check minimal monitoring Logstash version

### ISSUE THREAD

**Issue by dbeast-co** [dbeast-co/dbeast-monitoring-for-elastic-stack#11]
There is a difference in the input http_poller plugin.
Need to verify the minimal Logstash version, that should be installed for the Monitoring Logstash.

**Comment by tankha** [comment]
Minimal version for ssl_verification_mode in the http_poller plugin: 8.1.0
https://www.elastic.co/guide/en/logstash/current/logstash-8-1-0.html

**Comment by tankha** [comment]
README file updated
